In [10]:
import torch

In [11]:
dict = torch.load('../tb_logs/patch_nr_flow_material/version_05-10-2023_00:40:41/checkpoints/weights_curr.pth')

In [12]:
dict

{'net_state_dict': OrderedDict([('q0.loc',
               tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
                        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])),
              ('q0.log_scale',
               tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
                        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])),
              ('flows.0.flows.1.param_map.net.0.weight',
               tensor([[-0.0123, -0.1246,  0.1445,  ..., -0.0762, -0.1570,  0.0957],
                       [ 0.0110,  0.0848, -0.1920,  ..., -0.1923, -0.1620,  0.1181],
                       [ 0.0659, -0.1174,  0.0431,  ...,  0.2374,  0.1904,  0.1509],
                       ...,
                       [-0.0400,  0.0870,  0.1969,  ...,  0.0276,  0.0105, -0.0249],
                       [ 0.1455,  0.0171,  0.2091,  ...,  0.1586,  0.0786, -0.0433],
                       [

In [13]:
params = dict['hparams']
weights = dict['net_state_dict']

In [16]:
from flow_models import PatchNrModel

model = PatchNrModel()

TypeError: 'module' object is not callable

In [15]:
weights.keys()

dict_keys(['layers', 'hidden_layer_node_count', 'p_dim'])